stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw/data_version_1.csv
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw/data_version_1.csv
    - src/data/data_preprocessing.py
    outs:
    - data/processed/data_version_preprocessed.csv
  outlier:
    cmd: python src/data/outlier.py
    deps:
    - data/processed/data_version_preprocessed.csv
    - src/data/outlier.py
    outs:
    - data/processed/outlier_remove.csv
  impute_missing_values:
    cmd: python src/data/impute_missing_values.py
    deps:
    - data/processed/outlier_remove.csv
    - src/data/impute_missing_values.py
    outs:
    - data/processed/imputed_data.csv
  build_features:
    cmd: python src/features/build_features.py
    deps:
    - data/processed/imputed_data.csv
    - src/features/build_features.py
    outs:
    - data/processed/feature_selection.csv
  train_model:
    cmd: python src/model/train_model.py
    deps:
    - data/processed/feature_selection.csv
    - src/model/train_model.py
    outs:
    - models/model.pkl
  predict_model:
    cmd: python src/model/predict_model.py
    deps:
    - models/model.pkl
    - src/model/predict_model.py
    outs:
    - reports/metrics.json
